// Podcasts
export const PODCASTS_LIST_REQUEST = 'PODCASTS_LIST_REQUEST';
export const PODCASTS_LIST_SUCCESS = 'PODCASTS_LIST_SUCCESS';
export const PODCASTS_LIST_FAIL = 'PODCASTS_LIST_FAIL';

// Single podcast
export const SINGLE_PODCAST_REQUEST = 'SINGLE_PODCAST_REQUEST';
export const SINGLE_PODCAST_SUCCESS = 'SINGLE_PODCAST_SUCCESS';
export const SINGLE_PODCAST_FAIL = 'SINGLE_PODCAST_FAIL';

// Episodes of a podcast
export const EPISODES_LIST_REQUEST = 'EPISODES_LIST_REQUEST';
export const EPISODES_LIST_SUCCESS = 'EPISODES_LIST_SUCCESS';
export const EPISODES_LIST_FAIL = 'EPISODES_LIST_FAIL';
