// Podcasts
export const PODCASTS_LIST_REQUEST = 'PODCASTS_LIST_REQUEST';
export const PODCASTS_LIST_SUCCESS = 'PODCASTS_LIST_SUCCESS';
export const PODCASTS_LIST_FAIL = 'PODCASTS_LIST_FAIL';

// Single podcast
export const SINGLE_PODCAST_REQUEST = 'SINGLE_PODCAST_REQUEST';
export const SINGLE_PODCAST_SUCCESS = 'SINGLE_PODCAST_SUCCESS';
export const SINGLE_PODCAST_FAIL = 'SINGLE_PODCAST_FAIL';

// Episodes of a podcast
export const EPISODES_LIST_REQUEST = 'EPISODES_LIST_REQUEST';
export const EPISODES_LIST_SUCCESS = 'EPISODES_LIST_SUCCESS';
export const EPISODES_LIST_FAIL = 'EPISODES_LIST_FAIL';

// Player
export const CHANGE_PLAYER_STATUS = 'CHANGE_PLAYER_STATUS';

// User login
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';

// User register
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
