export const PODCASTS_LIST_REQUEST = 'PODCASTS_LIST_REQUEST';
export const PODCASTS_LIST_SUCCESS = 'PODCASTS_LIST_SUCCESS';
export const PODCASTS_LIST_FAIL = 'PODCASTS_LIST_FAIL';

// EPISODES == PODCAST
export const EPISODES_LIST_REQUEST = 'EPISODES_LIST_REQUEST';
export const EPISODES_LIST_SUCCESS = 'EPISODES_LIST_SUCCESS';
export const EPISODES_LIST_FAIL = 'EPISODES_LIST_FAIL';
